version: '3.1'
services:
  app:
    container_name: url_shortener_app
    build: .
    restart: always
    ports:
      - '3000:3000'
    depends_on:
      - db
    networks:
      - app
  db:
    container_name: url_shortener_db
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_DATABASE: url_shortener_db
      MYSQL_ROOT_PASSWORD: admin@123
    ports:
      - '3306:3306'
    networks:
      - app

networks:
  app:
    driver: bridge
